COWIN API SCRIPT
prathimacode-hub/Awesome_Python_Scripts pull request #182
Opened 2021-06-13 16:29 UTC by Bhuvanaa28

## Related Issue 

- COWIN API  Script 

- [x] LGM-SOC'21 Participant 

Closes: #140 

### Describe the changes you've made

-  Added the code to obtain details of vaccination sessions
-  Added README file
- Added screenshots in Images folder

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I executed the code for different test cases and obtained the expected output

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

![img4](https://user-images.githubusercontent.com/76595007/121815107-3a47af00-cc92-11eb-91fb-f6451cdba17c.PNG)

2021-06-13 16:35 UTC, prathimacode-hub requested changes
Changes to be done :

- Add libraries imported in "requirements.txt" file.
- Elaborate the README.md file
- Add appropriate comments in your project file wherever needed to get good understanding of it.

Kindly do the needful changes. @Bhuvanaa28

2021-06-13 18:33 UTC, thegautamkumarjaiswal requested changes
In python script, if you can add more comments will help to under code better.

2021-06-13 18:33 UTC, thegautamkumarjaiswal commented on APIScripts/COWIN API/README.md
> +CoWIN is a cloud-based IT solution for planning, implementation, monitoring, and evaluation of Covid-19 vaccination in India.
correct the CoWIN to COWIN.

2021-06-13 18:35 UTC, thegautamkumarjaiswal commented on APIScripts/COWIN API/README.md
> +CoWIN is a cloud-based IT solution for planning, implementation, monitoring, and evaluation of Covid-19 vaccination in India.
@prathimacode-hub Please review about more comments or code description.

2021-06-14 15:22 UTC, Bhuvanaa28 commented
> Changes to be done :
> 
> * Add libraries imported in "requirements.txt" file.
> * Elaborate the README.md file
> * Add appropriate comments in your project file wherever needed to get good understanding of it.
> 
> Kindly do the needful changes. @Bhuvanaa28

I have done the necessary changes Mam

2021-06-14 15:26 UTC, thegautamkumarjaiswal approved these changes
All's all working! Great.

2021-06-14 15:32 UTC, prathimacode-hub commented
@thegautamkumarjaiswal You're not allowed to review the PR's, as you being a LGMSOC participant. Kindly note this.

2021-06-14 15:34 UTC, prathimacode-hub approved these changes
Your PR is approved and merged successfully. You had done an amazing work. Keep rising. 🙌✔@Bhuvanaa28

2021-06-14 15:34 UTC, merged